export const DashboardScreen = () => {
  return (
    <div className="w-full min-h-full max-h-full overflow-y-scroll bg-[#f7f7f7] flex flex-col">
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
      <p>Dashboard</p>
    </div>
  );
};
